# -*- mode: ruby -*-
# vi: set ft=ruby :

# run: vagrant plugin install vagrant-omnibus

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.host     = "fj2.citozin.com"
    libvirt.username = "root"
    libvirt.connect_via_ssh = true
  end
  config.vm.box = "centos7"


  config.vm.define :ambari_server do |node|
    node.vm.network :forwarded_port, guest: 8080, host: 8080, id: 'Interface to Ambari Web and Ambari REST API'

    node.vm.hostname = 'server.ambari.ermolaev'
    node.vm.network   :private_network, ip: "10.20.30.40"
    node.vm.provision :hosts, sync_hosts: true

    node.vm.provider :libvirt do |domain|
      domain.memory = 8048
      domain.cpus = 4
    end

    node.omnibus.chef_version = :latest

    node.vm.provision :chef_solo do |chef|
      chef.cookbooks_path    = ["site-cookbooks", "cookbooks"]
      chef.roles_path        = "roles"
      chef.provisioning_path = "/tmp/vagrant-chef"
      chef.verbose_logging = true
      chef.add_role "ambari_server"
    end

  end



  config.vm.define :ambari_agent do |node|

    node.vm.hostname = 'agent.ambari.ermolaev'
    node.vm.network   :private_network, ip: "10.20.30.41"
    node.vm.provision :hosts, sync_hosts: true

    node.vm.provider :libvirt do |domain|
      domain.memory = 12048
      domain.cpus = 4
    end

    node.omnibus.chef_version = :latest

    node.vm.provision :chef_solo do |chef|
      chef.cookbooks_path    = ["site-cookbooks", "cookbooks"]
      chef.roles_path        = "roles"
      chef.provisioning_path = "/tmp/vagrant-chef"
      chef.verbose_logging = true
      chef.add_role "ambari_agent"
    end

  end

end
